controller_manager:
  ros__parameters:
    update_rate: 35
    use_sim_time: true

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

diff_drive_controller:
  ros__parameters:
    publish_rate: 35.0
    base_frame_id: base_link
    left_wheel_names: ['front_left_wheel_joint', 'rear_left_wheel_joint']
    right_wheel_names: ['front_right_wheel_joint', 'rear_right_wheel_joint']
    wheels_per_side: 2
    wheel_separation: 0.35
    wheel_radius: 0.024
    use_stamped_vel: false
    command_interfaces:
      - velocity
    state_interfaces:
      - velocity
      - position

joint_state_broadcaster:
  ros__parameters:
    publish_rate: 35.0
    joints:
      - front_left_wheel_joint
      - front_right_wheel_joint
      - rear_left_wheel_joint
      - rear_right_wheel_joint
